name: Release

on:
  release:
    types: [created]

env:
  GO_WEBEXT_VERSION: v0.4.1
  CHROME_API_VERSION: v2
  CHROME_APP_ID: bfjbejmeoibbdpfdbmbacmefcbannnbg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Set version via tag
        run: npm version --no-git-tag-version ${GITHUB_EVENT_RELEASE_TAG_NAME}
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
      - name: Resolve version
        run: |
          tag='${GITHUB_EVENT_RELEASE_TAG_NAME}'
          echo "VERSION=${tag#v}" >> "$GITHUB_ENV"
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
      - name: Build zip packages
        run: |
          npm run zip
          npm run zip:firefox
      - name: Submit to Firefox Add-ons
        uses: ninoseki/go-webext-action@c7216cca9656856a307ca5af64ddbb4c70831a99 # v1.1.0
        with:
          version: ${{ env.GO_WEBEXT_VERSION }}
          command: update
          browser: firefox
          file: .output/mitaka-${{ env.VERSION }}-firefox.zip
          source: .output/mitaka-${{ env.VERSION }}-sources.zip
          channel: listed
          cache: true
        env:
          FIREFOX_CLIENT_ID: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_CLIENT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
      - name: Update Chrome Web Store listing
        uses: ninoseki/go-webext-action@c7216cca9656856a307ca5af64ddbb4c70831a99 # v1.1.0
        with:
          version: ${{ env.GO_WEBEXT_VERSION }}
          command: update
          browser: chrome
          app-id: ${{ env.CHROME_APP_ID }}
          file: .output/mitaka-${{ env.VERSION }}-chrome.zip
          cache: true
        env:
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          CHROME_PUBLISHER_ID: ${{ secrets.CHROME_PUBLISHER_ID }}
      - name: Publish to Chrome Web Store
        uses: ninoseki/go-webext-action@c7216cca9656856a307ca5af64ddbb4c70831a99 # v1.1.0
        with:
          version: ${{ env.GO_WEBEXT_VERSION }}
          command: publish
          browser: chrome
          app-id: ${{ env.CHROME_APP_ID }}
          cache: true
        env:
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          CHROME_PUBLISHER_ID: ${{ secrets.CHROME_PUBLISHER_ID }}
