name: Browser Marketplace Submission

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install npm dependencies
        run: npm install

      - name: Build the archive
        run: npm run build

      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          archive: "web-ext-artifacts/mitaka-{version}.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
